title: Michel Storms
url: https://michelstorms.com
description: Freelance Apple Developer â€” custom software solutions, advice, design and programming services for Apple Platforms.

permalink: /blog/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .claude
